### ISSUE TITLE
broken formatting

### ISSUE THREAD

**Issue by tjhei** [dealii/publication-list#397]
these entries are formatted incorrectly starting with ", " in the second line:
![image](https://user-images.githubusercontent.com/1531285/189496652-7fea43c5-2dd4-4e5d-b9bb-e35cb6ef239f.png)

@bangerth You know the formatting schema best. Do you know what is happening here?

**Comment by bangerth** [comment]
Let's look at the first entry. It reads
```
@Misc{jodlbauer.langer.ea:matrix-free,
  author  = {Jodlbauer, Daniel and Langer, Ulrich and Wick, Thomas and Zulehner, Walter},
  title   = {Matrix-free Monolithic Multigrid Methods for Stokes and Generalized Stokes Problems},
  doi     = {10.48550/ARXIV.2205.15770},
  url     = {https://arxiv.org/abs/2205.15770},
  publisher = {arXiv},
  year    = {2022},
  copyright = {Creative Commons Attribution 4.0 International}
}
```
The template for the third line of an entry looks like this:
```
    \begin{howpublished}  \howpublished\end{howpublished}<!--
    -->\begin{publisher}, \format[HTMLChars]{\publisher}\end{publisher}<!--
      -->\begin{address}, \format[HTMLChars]{\address}\end{address}<!--
        -->\begin{pages}, pp. \format[FormatPagesForHTML]{\pages}\end{pages}<!--
         -->\begin{note}  (\format[HTMLChars]{\note})\end{note}<!--
-->\begin{archivePrefix}  \format[HTMLChars]{\archivePrefix}\end{archivePrefix}<!--
 -->\begin{primaryClass}  \format[HTMLChars]{\primaryClass}:\end{primaryClass}<!--
       -->\begin{eprint}\format[HTMLChars]{\eprint}\end{eprint}<!--
         -->\begin{year}, \format[HTMLChars]{\year}\end{year}<!--
                     -->.
```
Each `\begin{xxx}...\end{xxx}` is expanded if the bibtex record contains an `xxx={...}` entry. So for this record, there is no `howpublished=...` line, but there is a `publisher={...}` line and so the first thing that is expanded is the second line of the template, which starts with a comma.

These jabref templates are really very inconvenient because what text is being placed into the output is described by text substitution, not programmatically. I would much prefer if that text was just produced by a small JavaScript snippet or something wherein one can have if-then-else constructs. The second annoying component is that bibtex `@misc` entries are used for so many different things and don't always have the same fields populated. That just makes it different to write the template in a way that catches all possible uses of `@misc`. If output were programmatically generated, we could for example treat arXiv entries differently from other `@misc` entries.

In the case of the second entry you show above, this is an `@InBook` record for which we have no dedicated template. Rather, it is sent through the "generic template" that covers everything else.

Anyway, though, at least the `@misc` misformatting can easily be fixed. Patch forthcoming.
